### ISSUE TITLE
IntelliJ 2021 Support

### ISSUE THREAD

**Issue by NickGeek** [Phosphorus15/intellij-prolog#80] opened 2021-08-30 22:16 UTC
Hi,
The current plugin is marked as not supporting IntelliJ 2021. It would be awesome if there was an update to get it running.

Thanks!

**Comment by fan-tom** [comment] 2021-09-07 19:06
duplicate of #73

**Comment by Phosphorus15** [comment] 2022-09-20 06:56
Since 6bd2399 the plugin supports IntelliJ IDEA 2022.2.2, for which I shall consider this issue could be closed

**Closed by Phosphorus15** 2022-09-20 06:56 UTC
